### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Cynthia7979** [EnderKerman/wiki-translation-tool#1]
Let's add a license,<strike> although it does nothing but</strike> as it makes it seem "professional".

 Which one to add?

**Comment by EnderKerman** [comment]
I dont care anyways. I have asked one of my classmates to help design its UI and s/he says s/he doesnt care about how people will use his/her work either.

**Comment by Cynthia7979** [comment]
Got it. I'll use MIT then.
